name: 'iOS Danger'
description: 'Runs Danger Swift for PR analysis and commenting (with Fake CI mode for push events)'

inputs:
  github_token:
    description: 'GitHub token for PR comments'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Find open PR for this branch
      id: pr
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { owner, repo } = context.repo
          
          // If triggered by pull_request event, use that PR number directly
          const prFromEvent = context.payload.pull_request?.number
          if (prFromEvent) {
            core.setOutput("number", String(prFromEvent))
            console.log(`📋 PR #${prFromEvent} from event context`)
            return
          }

          // Otherwise, search for open PRs for this branch
          const branch = (context.ref || "").replace(/^refs\/heads\//, "")
          if (!branch) {
            core.setOutput("number", "")
            console.log("⚠️ Could not determine branch name")
            return
          }

          console.log(`🔍 Searching for open PRs for branch: ${branch}`)
          
          const prs = await github.rest.pulls.list({
            owner,
            repo,
            state: "open",
            head: `${owner}:${branch}`,
            per_page: 1,
          })

          if (prs.data[0]?.number) {
            core.setOutput("number", String(prs.data[0].number))
            console.log(`📋 Found open PR #${prs.data[0].number}`)
          } else {
            core.setOutput("number", "")
            console.log("ℹ️ No open PR found for this branch")
          }

    - name: Run Danger Swift (Fake CI mode)
      if: steps.pr.outputs.number != ''
      uses: danger/swift@3.22.1
      with:
        args: --failOnErrors --no-publish-check
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        DANGER_FAKE_CI: YEP
        DANGER_TEST_REPO: ${{ github.repository }}
        DANGER_TEST_PR: ${{ steps.pr.outputs.number }}

    - name: Skip Danger (no PR)
      if: steps.pr.outputs.number == ''
      shell: bash
      run: echo "⏭️ No open PR found - skipping Danger comments"
